version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_db
    environment:
      SA_PASSWORD: "YourPassword123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  jobportal.webapp:
    image: ${DOCKER_REGISTRY-}jobportalwebapp
    build:
      context: .
      dockerfile: JobPortal.WebApp/Dockerfile
    depends_on:
      - db  
    ports:
      - "65130:65130" 
      - "65131:443"  
    environment:
      - ConnectionStrings__JobPortalContextConnection=Server=db;Database=JobPortalDb;User Id=sa;Password=YourPassword123;
      - Urls__BaseUrl=https://localhost:65131  
volumes:
  sqlserver_data: